[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "check-ast" },
  { id = "check-case-conflict" },
  { id = "check-json" },
  { id = "check-merge-conflict" },
  { id = "check-toml" },
  { id = "check-yaml" },
  { id = "trailing-whitespace", args = ["--markdown-linebreak-ext=md"] },
  { id = "end-of-file-fixer" },
  { id = "mixed-line-ending" }
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.0"
hooks = [
  { id = "ruff-check", args = ["--fix", "--exit-non-zero-on-fix"] },
  { id = "ruff-format" }
]

[[repos]]
repo = "https://github.com/rbubley/mirrors-prettier"
rev = "v3.8.1"
hooks = [{ id = "prettier" }]

[[repos]]
repo = "https://github.com/biomejs/pre-commit"
rev = "v2.3.14"
hooks = [{ id = "biome-check" }, { id = "biome-format" }]

[[repos]]
repo = "https://github.com/psf/black-pre-commit-mirror"
rev = "26.1.0"
hooks = [{ id = "black" }]

[[repos]]
repo = "https://github.com/RobertCraigie/pyright-python"
rev = "v1.1.408"

[[repos.hooks]]
id = "pyright"
additional_dependencies = ["pydantic"]

[[repos]]
repo = "https://github.com/DetachHead/basedpyright-prek-mirror"
rev = "1.37.4"
hooks = [{ id = "basedpyright" }]
